### ISSUE TITLE
Command mentioned in Readme file does not create migration

### ISSUE THREAD

**Issue by drakegens** [spatie/laravel-webhook-client#104]
`php artisan vendor:publish --provider="Spatie\WebhookClient\WebhookClientServiceProvider" --tag="webhook-client-migrations"`

When i run this command, my migrations are not created.

However when i run the same command without the `--tag`, it does create the migration: `php artisan vendor:publish --provider="Spatie\WebhookClient\WebhookClientServiceProvider" --tag="webhook-client-migrations"`

I think there may be an issue with parsing the tag.

**Comment by freekmurze** [comment]
Are you running the latest version of the package?

**Comment by ikkarti** [comment]
same issue here

**Comment by leighgibbo** [comment]
+1 having same issue, with either `--tag="webhook-client-config"` or `--tag="webhook-client-migrations"`

I get the responses: 
**"No publishable resources for tag [webhook-client-config]."** and
**"No publishable resources for tag [webhook-client-migrations]."**, respectively.

**Comment by freekmurze** [comment]
I guess you are all not running the latest version of the package.

Closing this for now. If the problem persist, please make sure you are using the latest version.

**Comment by ehben83** [comment]
it seems that : composer require spatie/laravel-webhook-client
doesn't pull latest version... causing that problem

**Comment by hmaesta** [comment]
**Version 3** (current latest) requires PHP 8 and Laravel 8, as described in [CHANGELOG](https://github.com/spatie/laravel-webhook-client/blob/main/CHANGELOG.md#300---2021-07-25).

If you install without this requirements, you'll get version **2.7.5** which has a different `publish` command:

```
php artisan vendor:publish --provider="Spatie\WebhookClient\WebhookClientServiceProvider" --tag="config"
```

... as you can see in [README prior to v3](https://github.com/spatie/laravel-webhook-client/blame/2ff48c9d40c00487ca9dabf1da09e60817227ca6/README.md#L34).

**Comment by EricPaulson** [comment]
> 

Thank you for this!
