### ISSUE TITLE
V2 to V3 transition migration

### ISSUE THREAD

**Issue by l-alexandrov** [spatie/laravel-webhook-client#136]
Hi team,
Thanks for the great package. I am currently migrating from v2 to v3, but I found an issue in the `UPGRADING.md` file.

You need to make the `url` column nullable too on https://github.com/spatie/laravel-webhook-client/blob/dfefc451833f81fcb2d94b570e44a6a3770a5436/UPGRADING.md?plain=1#L6 , since most likely we will have other records in the table we have no value to set for.

**Comment by freekmurze** [comment]
Fixed 👍
