### ISSUE TITLE
There are no commands defined in the "vendor" namespace. 

### ISSUE THREAD

**Issue by TiagoPimentt** [spatie/laravel-webhook-client#147]
Hi guys

i'm try install webhook client and serve  in my aplication Lumen 9 but have problem.

1) This link https://github.com/spatie/laravel-webhook-client
2) put  `php artisan vendor:publish --provider="Spatie\WebhookServer\WebhookServerServiceProvider"`
result:  There are no commands defined in the "vendor" namespace. 

this print of my code: https://ibb.co/n1swVvB

I'm use laradock and i put code in container

what is problem?

**Comment by freekmurze** [comment]
We don't support Lumen. Try using the package in a full Laravel app.
