### ISSUE TITLE
Change error http response code

### ISSUE THREAD

**Issue by waltherjochen** [spatie/laravel-webhook-client#190]
> If $computedSignature does not match the value in the signature header, the package will respond with a 500 and discard the request.

Hi,
currently you can only change the valid response code. `respondToValidWebhook`. Is it also possible to change the error response code 500 server error?
e.g. Mailgun expects a 406 response code, if there is an issue.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/15231733/235342949-cfc0aff0-1456-44af-89b3-99192a091cc7.png">
https://documentation.mailgun.com/en/latest/user_manual.html#webhooks-1

Otherwise mailgun will just send the webhook again.

Thank you.

**Comment by freekmurze** [comment]
I'm thinking that if Mailgun sends a webhook, and the signature is wrong, that it is more likely that you did something wrong in your setup, and you want Mailgun to send the webhook again when you correct it.
