### ISSUE TITLE
Webhook Model can't be overridden

### ISSUE THREAD

**Issue by gogl92** [spatie/laravel-webhook-client#201]
When trying to use this package with MongoDB I tried to override the model `WebhookCall` as stated in the documentation, but I face issues because of the return types

This issue is being thrown while trying to implement [Laravel Stripe Webhooks](https://github.com/spatie/laravel-stripe-webhooks) but this is the root cause

```
[2023-12-11 01:54:30] local.ERROR: Spatie\StripeWebhooks\ProcessStripeWebhookJob::__construct():
Argument #1 ($webhookCall) must be of type Spatie\WebhookClient\Models\WebhookCall, App\Models\WebhookCall given, called in /var/www/html/vendor/spatie/laravel-webhook-client/src/WebhookProcessor.php on line 54 {"exception":"[object] (TypeError(code: 0): Spatie\\StripeWebhooks\\ProcessStripeWebhookJob::__construct(): Argument #1 ($webhookCall) must be of type Spatie\\WebhookClient\\Models\\WebhookCall, App\\Models\\WebhookCall given, called in /var/www/html/vendor/spatie/laravel-webhook-client/src/WebhookProcessor.php on line 54 at /var/www/html/vendor/spatie/laravel-stripe-webhooks/src/ProcessStripeWebhookJob.php:11)
```

So I think that the way to solve this issue is to have an Interface that the model use will implement, and the extension validates that this models are instances of this class, it will work as a contract (`WebhookCallContract`?) and the return types needed will use this instead of the model.

Methods can be added to this class if needed like:
```
storeWebhook();
headersToStore();
headerBag();
...
``` 

This way we allow the package to be more extendable.

**Comment by gogl92** [comment]
I can create a pull request to solve this issue

**Comment by paul-hellomolly** [comment]
Can we reopen this issue? I'm also having trouble using a different model that extends the `WebhookCall`.
