### ISSUE TITLE
Webhooks Attribute not found

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-webhook-client#25]
when using Route::webhooks('...', '...') i get an error like: 
`
InvalidArgumentException
Attribute [webhooks] does not exist.
`
and in the stack trace, the error is thrown on the web.php file

**Comment by AlbertoSinigaglia** [comment]
my fault, it was Laravel 6.0 that cache package and service, removed the files and works fine

**Comment by vinayaWD** [comment]
@AlbertoSinigaglia Which cache package were you deleted?

**Comment by LouisCharles70** [comment]
I didn't understand how you solved the problem ? I have the same problem and doing "php artisan cache:clear" didn't solve the problem

**Comment by AlbertoSinigaglia** [comment]
> I didn't understand how you solved the problem ? I have the same problem and doing "php artisan cache:clear" didn't solve the problem

If I don’t remember wrong, I’ve just run`php artisan route:clear ` and `php artisan cache:clear`

**Comment by AlbertoSinigaglia** [comment]
> @AlbertoSinigaglia Which cache package were you deleted?

Sorry for being late, just answered

**Comment by TheMangoTrain** [comment]
If you come across the error "Attribute [webhooks] does not exist"... and you've been working in other branches with different composer configs, you may need to simply run "composer install" again to make sure the library is actually installed. Your config/migrations/etc should still be in place.

**Comment by hondaman900** [comment]
Has anyone resolved this one? I'm on a Forger server, and running either `php artisan cache:clear` or `php artisan routes:clear` commands fail, but returning this error:

```
In RouteRegistrar.php line 92:
  Attribute [stripeWebhooks] does not exist.
```

Not sure what to do next and my site is broken.

**Comment by hondaman900** [comment]
FWIW, turns out that for me it was Composer running out of memory when installing a new package. Creating a new `composer.lock` on my local dev (using `composer update`) and then committing that to the live server (after much tweaking to resolve Git sync issues) fixed the issue.
