### ISSUE TITLE
Using Event instead of Job

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-webhook-client#26]
is there any way which i can use Event instad of job in order to manage a webhook?

**Comment by freekmurze** [comment]
Right now no events are fired when a webhook comes in. Feel free to send a PR for the event you'd like to see. Make sure to include tests and update the readme.

**Comment by AlbertoSinigaglia** [comment]
now, the handler of a WebHook event is a “ProcessWebhookJob”.. but it’s not a real Laravel job, right? What I mean is instead of using a class, just throw an event, like [This one ](https://github.com/spatie/laravel-stripe-webhooks#handling-webhook-requests-using-events)
