### ISSUE TITLE
small Docs on WebhookCall

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-webhook-client#27]
can you please create a small doc for WebhookCall? like for example how to access the request content... i'm currently using `$this->webhookCall->getAttribute('payload')` and then accessing the response field using arrays, but i don't know if it is the way it should be accessed

**Comment by freekmurze** [comment]
There's really not that much to say about it. It just a plain Eloquent model. To get attributes of it, you can just arrow notation

```php
$webhookCall->payload
```

**Comment by AlbertoSinigaglia** [comment]
Oh ok, perfect, thank you very much... I was thinking everything except a
as simple solution as this

Il giorno gio 10 ott 2019 alle 00:48 Freek Van der Herten <
notifications@github.com> ha scritto:
