### ISSUE TITLE
pass data from validation to Job

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-webhook-client#28]
Stripe for example use a Event constructor in order to validate the request: if the construction doesn't throw an exception, the validation is positive, otherwise the request is not valid. But at the moment, i need to requild the event inside the job. Is there any way to pass the evet from the validation to the job in order to not rebuild it ?

**Comment by freekmurze** [comment]
I don't know what you mean. Could you give a code example to clarify?

We have a decidated package for handling stripe webhooks: https://github.com/spatie/laravel-stripe-webhooks
