### ISSUE TITLE
Compressed payloads

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-webhook-client#32]
What do you think of adding an option to compress payloads when saving them to a database? Payloads _can_ grow quite large, and since it's all JSON data I figure there's lots to gain from compressing the data.

**Comment by brendt** [comment]
We could use [`gzcompress` ](https://www.php.net/manual/en/function.gzcompress.php)

**Comment by freekmurze** [comment]
I'd like to keep this package very simple. Inside the job that processes the webhook, you can take care of this yourself. You can copy the payload to some compressed storage and delete the row in the default table provided by this package.
