### ISSUE TITLE
is not a valid process webhook job class

### ISSUE THREAD

**Issue by chanar** [spatie/laravel-webhook-client#34]
Spatie\WebhookClient\Exceptions\InvalidConfig: `App\Handler\WebhookHandler` is not a valid process webhook job class. A valid class should implement `Spatie\WebhookClient\ProcessWebhookJob`. in file /Users/janarpalk/Projects/forexbook/vendor/spatie/laravel-webhook-client/src/Exceptions/InvalidConfig.php on line 35

Within webhook-client.php:
`'process_webhook_job' => App\Handler\WebhookHandler::class,`

Within WebhookHandler.php:
```<?php

namespace App\Handler;

use Spatie\WebhookClient\ProcessWebhookJob;

class WehbhookHandler extends ProcessWebhookJob {
    public function handle() {
        Log::debug('test');
        Log::debug($this->webhookCall);
    }
}
```

uh?

**Comment by chanar** [comment]
We**hb**hookHandler 😀

**Comment by ariopangarih** [comment]
i found the same problem, it keeps logging error => `` is not a valid process webhook job class. A valid class should implement `Spatie\WebhookClient\Jobs\ProcessWebhookJob`. {"exception":"[object].
![Screen Shot 2022-01-14 at 10 52 32](https://user-images.githubusercontent.com/50353624/149448722-bb404fe1-ae73-421d-a8b9-42bc7f79fdf5.png)

**Comment by ariopangarih** [comment]
Hi, first i appreciate your works for making webhook library. I found the same problem here. It keeps returning error for invalid process webhook job class.
Here the WebhookHandler and ProcessWebhookJob screenshots.

![Screen Shot 2022-01-14 at 10 56 01](https://user-images.githubusercontent.com/50353624/149449006-0750f641-cd6b-4ef1-961b-1b1f849d6f5f.png)
![Screen Shot 2022-01-14 at 10 56 09](https://user-images.githubusercontent.com/50353624/149449015-1fc8a076-b67d-4542-97d9-a0e3a2bc5a33.png)
