### ISSUE TITLE
syntax error, unexpected '$url' (T_VARIABLE), expecting ')'

### ISSUE THREAD

**Issue by SarasVe** [spatie/laravel-webhook-client#39]
Hello, I've got syntax error after fresh install on laravel app for woocommerce webhook handle. Here is what I get:
```
Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected '$url' (T_VARIABLE), expecting ')'
```
```
::Composer\Autoload\includeFile:28
vendor/spatie/laravel-webhook-client/src/WebhookClientServiceProvider.php:28
```
And the line is:
`Route::macro('webhooks', fn(string $url, string $name = 'default') => Route::post($url, '\Spatie\WebhookClient\WebhookController')->name("webhook-client-{$name}"));`

**Comment by freekmurze** [comment]
Make sure to have PHP 7.4 installed.

**Comment by DLO33** [comment]
I am also encountering this error. I have php 7.4.2 installed.

PHP 7.4.2 (cli) (built: Feb  5 2020 16:50:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies


![image](https://user-images.githubusercontent.com/35256407/74330391-b6ec2400-4de5-11ea-8754-09e9a878a8a2.png)

**Comment by Globulard** [comment]
Same issue here using PHP 7.4.1. I don't get why @freekmurze closed it this fast.

**Comment by mvrska** [comment]
@DLO33 @Globulard I had this issue, too, but when I doublechecked I didn't really have PHP 7.4, check in the context tab by the stack trace, just in case you have multiple php versions

**Comment by kennblvnp** [comment]
same issue with 7.4.4.

**Comment by blessingdube** [comment]
If anyone is using Docker, you will need to maker sure that the php version in your container is also set to PHP 7.4. The error syntax error you are receiving is actually coming from the container's PHP version and not your local PHP version.

If using laradock, this is pretty easy to resolve.

First edit your laradock `.env` file on line 42 and set the `PHP_VERSION` value to `7.4`

Then run `docker-compose build php-fpm`, followed by `docker-compose build workspace`.

Once that's done, run `docker-compose down` and then bring your containers up as you normally would.

I hope this helps!

**Comment by DLO33** [comment]
> @DLO33 @Globulard I had this issue, too, but when I doublechecked I didn't really have PHP 7.4, check in the context tab by the stack trace, just in case you have multiple php versions

@mvrska appreciate the reply, finally got around to having a look at this and you were correct. Context was showing an older version of php. Updated Ngix and everything seems to be good now :)

**Comment by LinuxSwiss** [comment]
Good evening all. Plsss I encounter de same problem but is not telling me to be expecting any ')' is just like that. Just check it out here please and help me
![IMG_20210624_100707_289](https://user-images.githubusercontent.com/86290866/123303888-33ccf900-d516-11eb-8222-3137f21b02e4.jpg)

**Comment by mvrska** [comment]
> Good evening all. Plsss I encounter de same problem but is not telling me to be expecting any ')' is just like that. Just check it out here please and help me
> ![IMG_20210624_100707_289](https://user-images.githubusercontent.com/86290866/123303888-33ccf900-d516-11eb-8222-3137f21b02e4.jpg)

is this even laravel?

**Comment by LinuxSwiss** [comment]
> > Good evening all. Plsss I encounter de same problem but is not telling me to be expecting any ')' is just like that. Just check it out here please and help me
> > ![IMG_20210624_100707_289](https://user-images.githubusercontent.com/86290866/123303888-33ccf900-d516-11eb-8222-3137f21b02e4.jpg)
> 
> is this even laravel?

well I don't really know I got my code from the company by name bulksmsnigeria.com. 
And I integrated it using just php.

**Comment by LinuxSwiss** [comment]
And this error is showing.

**Comment by LinuxSwiss** [comment]
![IMG_20210707_070548_673](https://user-images.githubusercontent.com/86290866/124708345-1292e200-def2-11eb-89be-3baf2a7b2f81.jpg)

**Comment by LinuxSwiss** [comment]
This is the code

**Comment by vicmi-dev** [comment]
> Make sure to have PHP 7.4 installed.

the issue for me was that I had changed the php version but I had not restarted apache. Thank you for the hint!
