### ISSUE TITLE
Error handling could be more precise

### ISSUE THREAD

**Issue by Leamsi9** [spatie/laravel-webhook-client#46]
Thanks for a package I'm enjoying sinking my teeth into.

I forgot to rerun my migrations so the web calls database was AWOL. What I got was an "Invalid Signature" error, so I naturally spent a while debugging the signature config and secret. It was not until I commented out the `throw WebhookFailed::invalidSignature();` in `WebhookProcessor.php` that I got a missing table error, which obviously had nothing to do with the signature being invalid. Once I ran my migrations my signature was fine and all worked as intended.

Might be worth differentiating signature errors from other errors?

**Comment by freekmurze** [comment]
Feel free to PR improvements (with tests) around this 👍
