### ISSUE TITLE
Make work with no header...

### ISSUE THREAD

**Issue by leeovery** [spatie/laravel-webhook-client#5]
Hey,

Im happy to do a PR but thought Id check first...

I have a need to setup webhooks from a third part app. But as its a third party sending the data I cant control how and if they send headers.

I tried setting up a SignatureValidator which just returns true, but the package rejects empty headers early.

How do you feel about integrating the signature check into the validator? That way a custom validator would have full control over that process, and would enable people to avoid headers altogether if desired.

Thanks for another amazing package!!! Ill be sending postcards very soon when I launch :)

Lee

**Comment by freekmurze** [comment]
I'd accept a fully tested, non-breaking PR for this. Thank you for the kind words. Looking forward to the postcards.
