### ISSUE TITLE
Support the same PHP versions as Laravel

### ISSUE THREAD

**Issue by jmsfwk** [spatie/laravel-webhook-client#51]
Verison 2.4.0 (spatie/laravel-webhook-client@3d0ae24a99) removed support for PHP < 7.4 while [Laravel supports PHP >= 7.2.5](https://laravel.com/docs/7.x#server-requirements)

I've tagged a version 2.3.1 with support in my fork jmsfwk/laravel-webhook-client@8fe68f5.

It would be great if you could create a `2.3.x` branch so I could make a pull request.

**Comment by freekmurze** [comment]
We will only support PHP 7.4 for this package. Feel free continuing to use your fork.
