### ISSUE TITLE
Delayed Dispatching

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-webhook-client#63]
Hi,
I was lookig at the package configuration for the past 15 minutes, but I'm no table to find how to postpone the jobs for example for 5 minutes, is there a way to do it? 

Thank you
PS: i've also checked the old issues but found nothing like this

Referring to https://laravel.com/docs/7.x/queues#delayed-dispatching

**Comment by AlbertoSinigaglia** [comment]
I may have solved this problem in this way
```PHP
public function __construct(WebhookCall $webhookCall)
{
    parent::__construct($webhookCall);
    $this->delay(now()->addMinutes(10 /* my dalay */));
}
```
Can you please confirm if this is the right way to do it?

**Comment by freekmurze** [comment]
Seems like a good way to go about it.
