### ISSUE TITLE
Issue with invalidProcessWebhookJob

### ISSUE THREAD

**Issue by brmo** [spatie/laravel-webhook-client#64]
Howdy, I am getting this and cannot seem to resolve it.

Argument 1 passed to Spatie\\WebhookClient\\Exceptions\\InvalidConfig::invalidProcessWebhookJob() must be of the type string, null given, called in /shared/httpd/yccv7/vendor/spatie/laravel-webhook-client/src/WebhookConfig.php on line 56 at /shared/httpd/yccv7/vendor/spatie/laravel-webhook-client/src/Exceptions/InvalidConfig.php:39)

I am using Laravel 7, Cashier 10.7.1, and the stripe webhooks package. When I get a response from the Stripe CLI forwarding over to the website, I get the above. If I send it to the normal Laravel Cashier routes, everything is fine and I get a 200 OK.  I am not using a custom job, I am just trying to use the default "\Spatie\StripeWebhooks\ProcessStripeWebhookJob::class," model.

**Comment by freekmurze** [comment]
That strange, could your PR a failing test for us to fix?

**Comment by brmo** [comment]
I was able to do a cache:clear and it works now.
