### ISSUE TITLE
Typed property Spatie\WebhookClient\ProcessWebhookJob::$webhookCall must be an instance of Spatie\WebhookClient\Models\WebhookCall, Illuminate\Contracts\Database\ModelIdentifier used

### ISSUE THREAD

**Issue by aaronr0207** [spatie/laravel-webhook-client#67]
I'm receiving the calls but when it reachs the processor it fails.

Jobs at db: 
![image](https://user-images.githubusercontent.com/7554753/87156271-b5ebef80-c2bc-11ea-93b7-480f74eaec11.png)

Processor:

![image](https://user-images.githubusercontent.com/7554753/87156803-88ec0c80-c2bd-11ea-88ee-cd8255ddaa9b.png)

Config:

![image](https://user-images.githubusercontent.com/7554753/87156855-a325ea80-c2bd-11ea-979d-66afc201506a.png)

And this is the full given error: 
![image](https://user-images.githubusercontent.com/7554753/87156542-1e3ad100-c2bd-11ea-9fdb-a629c0c8e12e.png)

Stacktrace:

![image](https://user-images.githubusercontent.com/7554753/87156717-65c15d00-c2bd-11ea-8a23-92003d91e665.png)

**Comment by freekmurze** [comment]
I'm thinking this is due you using an old version of Laravel. Could you upgrade to the latest version?

If the problem persists, please PR a failing test for me to look at.
