### ISSUE TITLE
Spatie\WebhookClient\Exceptions\InvalidConfig: `app\Classes\MailGunValidator` is not a valid signature validator class. 

### ISSUE THREAD

**Issue by ksorbo** [spatie/laravel-webhook-client#69]
I have created a new class to validate the signature and placed it in app\Classes\MailGunValidator
In config/webhook-client.php I have

`           'signature_validator' => \app\Classes\MailGunValidator::class,`

My valildator class is:

`<?php

namespace App\Classes;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
//use Spatie\WebhookClient\SignatureValidator\SignatureValidator;
use Spatie\WebhookClient\WebhookConfig;

class MailGunValidator implements \Spatie\WebhookClient\SignatureValidator\SignatureValidator
{
    public function isValid(Request $request, WebhookConfig $config): bool
    {
       $secret = config('webhook-client.signing_secret');
       $timestamp =   $request->header('timestamp');
       $token = $request->header('token');
       $signature = $request->header('signature');
       $compareTo = hash_hmac('sha256',$timestamp.$token,$secret);
       Log::info('IsValid:'. $signature."\n".$compareTo);
       return hash_equals($signature,$compareTo);
    }
}
`
Why is the package not recognizing my class as implementing the SignatureValidator?

**Comment by spam-n-eggs** [comment]
This seems to be happening for *any* custom SignatureValidator.  @Sou1Aced and I were working on something today to try to write a signature validator (for testing) that allowed anything to be in the signature block.  it fails on the `is_subclass_of()` call on line 37 in WebhookConfig.php.  I am wondering if something with that method has changed in PHP 7.4 where it doesn't work with interfaces suddenly.

**Comment by freekmurze** [comment]
The tests seem to indicate that this functionality is working just fine. 

Please submit a failing test for me to look at. Thanks!

**Comment by Santukon** [comment]
Same problem here.
@ksorbo could you found the solution?

**Comment by bartclaeys** [comment]
Same problem here, what's going on?
