### ISSUE TITLE
JSON column type for payload?

### ISSUE THREAD

**Issue by BrekiTomasson** [spatie/laravel-webhook-client#70]
In the migration `create_webhook_calls_table.php.stub`, the `payload` column is defined using `$table->text()`. This means that I'm unable to use queries like `WebhookCall::where('payload->type', 'invoice.paid')->first();` as the database (Postgres in this case) doesn't understand how to query text columns as JSON.

Would it be possible to update the migration to use a `$table->json()` definition if it detects that that the driver used in the connection defined in `config('database.default')` supports JSON columns?

**Comment by freekmurze** [comment]
I'll consider changing this in the next major version of the package. For now, make the change in the migration that you published in your project.
