### ISSUE TITLE
Could not find the configuration for `default`

### ISSUE THREAD

**Issue by kalitk0** [spatie/laravel-webhook-client#77]
I am getting the following error:
Spatie\WebhookClient\Exceptions\InvalidConfig: Could not find the configuration for `default` in file /var/www/html/vendor/spatie/laravel-webhook-client/src/Exceptions/InvalidConfig.php on line 14

This is the configuration file /config/webhook-client.php

`return [
    'configs' => [
        [
            'name' => 'default',
			'signing_secret' => env('WEBHOOK_CLIENT_SECRET'),
			'signature_header_name' => 'Signature',
			'signature_validator' => \Spatie\WebhookClient\SignatureValidator\DefaultSignatureValidator::class,
			'webhook_profile' => \Spatie\WebhookClient\WebhookProfile\ProcessEverythingWebhookProfile::class,
			'webhook_model' => \Spatie\WebhookClient\Models\WebhookCall::class,
			'process_webhook_job' => App\Handler\ProcessWebhook::class,
        ],
    ],
];`

**Comment by freekmurze** [comment]
Hi,

could you please create an discussion in the Q&A category for this?
