### ISSUE TITLE
Change to Signature Validation

### ISSUE THREAD

**Issue by olimortimer** [spatie/laravel-webhook-client#80]
Is there any way of altering the behaviour, to validate the signature differently?

The system I am integrating with creates the signature based on other data it sends back, so I need to validate against the password I send to them, and the airbillnumber they respond with;

> This is calculated by adding the API Key used and the returned airbill number and hashing with MD5
signature = MD5 (password + airbillnumber)

Many thanks!

**Comment by freekmurze** [comment]
Here you go: https://github.com/spatie/laravel-webhook-client#creating-your-own-signature-validator
