### ISSUE TITLE
Why not $this->loadMigrationsFrom(...)?

### ISSUE THREAD

**Issue by bilogic** [spatie/laravel-webhook-client#87]
I was wondering if it would make using this package easier by using `$this->loadMigrationsFrom` to auto discover migrations?

**Comment by freekmurze** [comment]
We're now using our own `PackageServiceProvider` to load migrations.

**Comment by bilogic** [comment]
wow, just discovered https://github.com/spatie/laravel-package-tools
I have something very similar, but yours put mine to shame 🤦‍♂️
