### ISSUE TITLE
Process Webhook without dispatching job

### ISSUE THREAD

**Issue by matthewhutchings** [spatie/laravel-webhook-client#9]
I need to process a webhook that returns the response, but ProcessWebhookJob implements ShouldQueue.

Is it possible to override this?

**Comment by freekmurze** [comment]
Currently this is not possible without introducing breaking changes. I'll revisit this issue when creating a new major version.

**Comment by oskarbet** [comment]
Is there any news on this issue?

**Comment by RdeWilde** [comment]
This would make things more simple.

**Comment by RdeWilde** [comment]
@freekmurze shouldn't this issue be re-opened if it's still on the roadmap?

**Comment by freekmurze** [comment]
The label will make me look at this issue again whenever I should create a new major version.

**Comment by matthewhutchings** [comment]
4 years later I find myself needing this feature again for another project, any progress?

We have 10 incoming webhooks and need 3 of them to return on sync rather than running as a job - only way is to remove them from this package at the moment.
