### ISSUE TITLE
Without validation

### ISSUE THREAD

**Issue by spekulatius** [spatie/laravel-webhook-client#91]
Hello @freekmurze,

I was wondering if you think it would make sense to allow the validator to be `null` for completely unvalidated webhooks. 

I know it's not recommended, but some services don't offer webhooks with signatures or other signing methods. 

I'm adding a custom validator that simply returns `true` for these services atm.

If you would consider this a worthy change, can would prepare a PR for your consideration.

Cheers,
Peter

**Comment by freekmurze** [comment]
> I'm adding a custom validator that simply returns true for these services atm.

I'm thinking that is the way to go. 

> If you would consider this a worthy change, can would prepare a PR for your consideration.

Let's not add complexity for something that is already possible to handle (and kinda of an edge case imho)

**Comment by mshamaseen** [comment]
what about tests? how can I run the test without validation?
